#!/bin/bash

echo "Enter a number:"
read n

fact=1

for (( i=1; i<=n; i++ ))
do
  fact=$((fact * i))
done

echo "Factorial of $n is: $fact"


#!/bin/bash

echo "Using FOR loop:"
for i in {1..5}
do
  echo $i
done

echo "Using WHILE loop:"
i=1
while [ $i -le 5 ]
do
  echo $i
  i=$((i+1))
done
echo "Using UNTIL loop:"
i=1
until [ $i -gt 5 ]
do
  echo $i
  i=$((i+1))
done




#!/bin/bash

echo "Enter a number:"
read n

i=2
flag=0

while [ $i -lt $n ]
do
  if [ $((n % i)) -eq 0 ]
  then
    flag=1
    break
  fi
  i=$((i + 1))
done

if [ $flag -eq 0 ]
then
  echo "$n is a Prime Number"
else
  echo "$n is Not a Prime Number"
fi




#!/bin/bash

echo "Enter value of N:"
read n

i=1
sum=0

while [ $i -le $n ]
do
  sum=$((sum + i))
  i=$((i + 1))
done

echo "Sum of first $n numbers is: $sum"





#!/bin/bash

echo "Enter a number:"
read n

echo "Table of $n is:"

for i in {1..10}
do
  result=$((n * i))
  echo "$n x $i = $result"
done
